### PR TITLE
Fix error message when long number fails to parse

### PR DESCRIPTION
**Pull request by atifaziz**

### CODE REVIEW

**Comment by polterguy** [comment]
Thx mate :)

**Comment by atifaziz** [comment]
What's the reason for closing without merging? 😕

**Comment by polterguy** [comment]
Didn't I merge ...?
I was 100% certain I actually did a merge, sorry, I am a not used to merging patches through the web interface like this :)

I'll give another try at it ...

**Comment by polterguy** [comment]
Sorry about that, I think I've done it correctly now ...

**Comment by atifaziz** [comment]
👏

**Pull request merged**
